#!/usr/bin/env python3

import os
import sys
from analyzer import Analyzer
from termcolor import colored
from analyzer import Analyzer
from helpers import get_user_timeline 

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile word")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    judgement = get_user_timeline(sys.argv[1], count=200)
    if judgement is False:
        sys.exit(0)
    else:
        for tweet in judgement:
            score = analyzer.analyze(tweet)
            if score > 0.0:
                print(colored(str(score) + " " + tweet, "green"))
            elif score < 0.0:
                print(colored(str(score) + " " + tweet, "red"))
            else:
                print(colored(str(score) + " " + tweet, "yellow"))      
                
if __name__ == "__main__":
    main()



